import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import { useTaskStore } from "./../hooks"
import TaskCard from "../components/taskcard";
import { Task } from "./../hooks";
import Modal from "../components/modal";
import { useEffect, useState } from "react";
import NewTask from "../components/newtask";
const { DateTime, Duration} = require("luxon");

const Home: NextPage = () => {
  const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);
  const tasks = useTaskStore(state => state.tasks);
  const [modalOpen, setModalOpen] = useState<boolean>(false)
  const addTask = useTaskStore(state => state.addTask);

  function addDummyTask(){
    const exampleTask:Task= {
      id: tasks.length,
      title: "Example Task",
      description: "This is an example task",
      status: "todo",
      createdAt: DateTime.now(),
      deadline: "later",
      duration: "1h",
      priority: 1,
      progress: 0
    }
    addTask(exampleTask);
  }

  return (
    <>
      <Head>
        <title>Prior</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="portal-out">
      <div style={{filter: modalOpen?"brightness(0.4)":"brightness(1.0)"}} className="w-screen bg-slate-700 gap-5 text-white border-white min-h-screen flex flex-col justify-center items-center p-4 overflow-y-scroll">
        <h1 className="text-4xl font-bold">Hello World</h1>
        <div className="w-3/4 flex flex-row flex-wrap">{tasks.map(task => <TaskCard key={task.id} id={task.id}/>)}</div>
        <button onClick={addDummyTask}>Add task</button>
        <NewTask setOpen={setModalOpen} />
      </div>
      </div>
      
    </>
  );
};

export default Home;
