import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import { useTaskStore } from "./../hooks"
import TaskCard from "../components/taskcard";
import { Task } from "./../hooks";
import { useEffect, useState } from "react";
import NewTask from "../components/newtask";
import { importanceToColor } from "../utils/colors";
const { DateTime, Duration} = require("luxon");
import { parseInput } from "../utils/nlp";
import { nanoid } from 'nanoid';

const Home: NextPage = () => {
  const hello = trpc.useQuery(["example.hello", { text: "from tRPC" }]);
  const tasks = useTaskStore(state => state.tasks);
  const [modalOpen, setModalOpen] = useState<boolean>(false)
  const addTask = useTaskStore(state => state.addTask);

  function addDummyTask(){
    const exampleTask:Task= {
      id: nanoid(),
      title: "Example Task",
      description: "This is an example task",
      start: DateTime.now(),
      end: DateTime.now().plus({days: 14}),
      duration: Duration.fromObject({days: 7}),
      priority: 1,
      progress: 0.0
    }
    addTask(exampleTask);
  }
  return (
    <>
      <Head>
        <title>Prior</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id="portal-out">
      <div style={{filter: modalOpen?"brightness(0.4)":"brightness(1.0)"}} className="w-screen bg-slate-700 gap-5 text-white border-white min-h-screen flex flex-col justify-center items-center p-4 overflow-y-scroll">
        <h1 className="text-4xl font-bold">Hello World</h1>
        <div className="h-20 w-full flex flex-row">{[0.05, 0.15, 0.25, 0.35, 0.45, 0.55, 0.65, 0.75, 0.85, 0.95, 1.05].map(score => (<div key={score} className={importanceToColor(score) + " h-30 w-full"}></div>))}</div>
        <div className="w-3/4 flex flex-row items-center justify-center flex-wrap">{tasks.map(task => <TaskCard key={task.id} id={task.id}/>)}</div>
        <button onClick={addDummyTask}>Add task</button>
        <NewTask setOpen={setModalOpen} />
      </div>
      </div>
      
    </>
  );
};

export default Home;
